name: AutoFix PR

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  pre_job:
      name: Path match check
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
        should_skip: ${{ steps.skip_check.outputs.should_skip }}
      steps:
        - id: skip_check
          uses: fkirc/skip-duplicate-actions@master
          with:
            github_token: ${{ github.token }}
            paths_ignore: '["**.po", "**.json"]'

  autofix:
    name: Autofix Pull Request Linting Errors
    needs: pre_job
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
      - name: Get yarn cache directory path
        id: yarn-cache-dir-path
        run: echo "dir=$(yarn cache dir)" >> $GITHUB_OUTPUT
      - name: Cache Node.js modules
        uses: actions/cache@v4
        with:
          path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        run: |
          yarn --frozen-lockfile
          npm rebuild node-sass

      - uses: pre-commit/action@v3.0.0
      - uses: pre-commit-ci/lite-action@v1.0.2
      - name: Commit and push autofixed changes
        if: always()
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Autofix linting errors"
          git push origin ${{ github.head_ref }}
